import { z } from 'zod';
import { DrSyntaxOutputSchema } from './dr-syntax-schemas';
import { AegisAnomalyScanOutputSchema } from './aegis-schemas';
import { ContactSchema, DeleteContactOutputSchema } from '@/ai/tools/crm-schemas';
import { BillingUsageSchema } from '@/ai/tools/billing-schemas';
import { VinDieselOutputSchema } from './vin-diesel-schemas';

// Schemas from the original BEEP agent, preserved for the public contract.
const LaunchableAppTypeSchema = z.enum([
  'file-explorer',
  'terminal',
  'echo-control',
  'pam-poovey-onboarding',
  'beep-wingman',
  'infidelity-radar',
  'vin-diesel',
]);

export const AppToLaunchSchema = z.object({
  type: LaunchableAppTypeSchema,
  title: z.string().optional().describe('A specific title for this app instance, if applicable. Otherwise, the default will be used.'),
  description: z.string().optional().describe('A specific description for this app instance, if applicable. Otherwise, the default will be used.'),
});

const CrmCreationReportSchema = z.object({
    action: z.literal('create'),
    report: ContactSchema.describe('The details of the newly created contact.'),
});

const CrmUpdateReportSchema = z.object({
    action: z.literal('update'),
    report: ContactSchema.describe('The details of the updated contact.'),
});

const CrmListReportSchema = z.object({
    action: z.literal('list'),
    report: z.array(ContactSchema).describe('A list of contacts.'),
});

const CrmDeletionReportSchema = z.object({
    action: z.literal('delete'),
    report: DeleteContactOutputSchema.describe('The result of the deletion operation.'),
});

const CrmAgentReportSchema = z.discriminatedUnion('action', [
    CrmCreationReportSchema,
    CrmUpdateReportSchema,
    CrmListReportSchema,
    CrmDeletionReportSchema,
]);

const BillingAgentReportSchema = z.object({
    action: z.literal('get_usage'),
    report: BillingUsageSchema.describe('The billing usage details.'),
});


export const AgentReportSchema = z.discriminatedUnion('agent', [
  z.object({
    agent: z.literal('dr-syntax'),
    report: DrSyntaxOutputSchema.describe(
      'The full report object from the Dr. Syntax agent.'
    ),
  }),
  z.object({
    agent: z.literal('aegis'),
    report: AegisAnomalyScanOutputSchema.describe(
      'The full report object from the Aegis agent.'
    ),
  }),
   z.object({
    agent: z.literal('crm'),
    report: CrmAgentReportSchema,
  }),
  z.object({
    agent: z.literal('billing'),
    report: BillingAgentReportSchema,
  }),
  z.object({
    agent: z.literal('vin-diesel'),
    report: VinDieselOutputSchema.describe(
        'The full report from the VIN Diesel agent.'
    ),
  }),
]);

export const UserCommandInputSchema = z.object({
  userCommand: z.string().describe('A natural language command from the user about what they want to do or launch.'),
});
export type UserCommandInput = z.infer<typeof UserCommandInputSchema>;

export const UserCommandOutputSchema = z.object({
  appsToLaunch: z.array(AppToLaunchSchema).describe('An array of Micro-Apps that BEEP has determined should be launched on the Canvas based on the user command. This can be empty.'),
  agentReports: z.array(AgentReportSchema).optional().describe("An array of reports generated by other agents after BEEP delegated tasks to them. This should be populated with the result of any tool calls."),
  suggestedCommands: z.array(z.string()).describe('If no specific app can be launched or action taken, provide an array of suggested commands or actions the user could take next. This is for conversational repair.'),
  responseText: z.string().describe('A natural language response to the user confirming the action or asking for clarification.'),
});
export type UserCommandOutput = z.infer<typeof UserCommandOutputSchema>;
