
// src/config/artifacts.ts

export type ArtifactType = 'MICRO_APP' | 'CHAOS_CARD';

export type ArtifactManifest = {
  id: string; // Unique key, e.g., 'spectre-intelligence-suite' or 'GEOLOGIC_TIME'
  type: ArtifactType;
  name: string;
  description: string;
  author?: string; // For MicroApps
  creditCost: number;
  priceModel: 'one-time' | 'subscription' | 'included' | 'tribute';
  imageUrl: string;
  imageHint: string;
  isFeatured?: boolean;
  tags?: string[];
  branding?: {
    poweredBy?: string[];
    forgedIn?: string;
    callsign?: string;
    doctrine?: string;
  };
  
  // Micro-App specific fields
  defaultSize?: { width: number; height: number };
  permissionsRequired?: string[];
  
  // Chaos Card specific fields
  cardClass?: 'AESTHETIC' | 'AGENTIC' | 'SYSTEMIC' | 'SYNDICATE' | 'BOON';
  rarity?: 'COMMON' | 'UNCOMMON' | 'RARE' | 'MYTHIC';
  systemEffect?: string;
  durationMinutes?: number;
};


// Merged and unified manifest
export const artifactManifests: ArtifactManifest[] = [
  // --- MICRO APPS ---
  {
    id: 'file-explorer',
    type: 'MICRO_APP',
    name: "The Scribe's Archive",
    author: 'ΛΞVON OS',
    description: 'A sentient library where every piece of data has a purpose, a context, and a living relationship with your agents.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'library crystal knowledge',
    defaultSize: { width: 550, height: 400 },
    permissionsRequired: [],
    tags: ['core', 'utility', 'data'],
  },
  {
    id: 'terminal',
    type: 'MICRO_APP',
    name: 'Terminal',
    author: 'ΛΞVON OS',
    description: 'Direct command-line access to the BEEP agent.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'code command line',
    defaultSize: { width: 500, height: 350 },
    permissionsRequired: [],
    tags: ['core', 'utility', 'developer'],
  },
  {
    id: 'admin-console',
    type: 'MICRO_APP',
    name: 'Admin Console',
    author: 'ΛΞVON OS',
    description: 'Manage users, monitor system health, and configure workspace settings. For the Architect only.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dashboard settings users',
    defaultSize: { width: 700, height: 550 },
    permissionsRequired: ['OWNER_ONLY'],
  },
  {
    id: 'ritual-quests',
    type: 'MICRO_APP',
    name: 'Ritual Quests',
    author: 'The Chronicler',
    description: 'Accept personalized challenges from the OS to guide your journey and increase your Vow Alignment Score.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'scroll quest star',
    defaultSize: { width: 380, height: 450 },
    permissionsRequired: [],
    tags: ['core', 'utility', 'gamification', 'covenant'],
  },
  {
    id: 'command-and-cauldron',
    type: 'MICRO_APP',
    name: "Command & Cauldron",
    author: 'Aegis Subsystems',
    description: 'A standalone, sovereign Security Ritual Engine. Forge and enforce arcane security policies across your entire digital empire.',
    creditCost: 999,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cauldron magic ritual',
    defaultSize: { width: 700, height: 550 },
    permissionsRequired: ['ADMIN'],
    tags: ["security", "ritual", "automation", "enterprise", "api"],
  },
  {
    id: 'integration-nexus',
    type: 'MICRO_APP',
    name: 'Integration Nexus',
    author: 'ΛΞVON OS',
    description: 'The Conductor of Worlds. Connect, configure, and manage data flows with external services like Slack, Google, and Stripe.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'nodes connections api',
    defaultSize: { width: 450, height: 500 },
    permissionsRequired: ['ADMIN'],
    tags: ['core', 'utility', 'api', 'integrations'],
  },
  {
    id: 'contact-list',
    type: 'MICRO_APP',
    name: 'Contact List',
    author: 'ΛΞVON OS',
    description: 'A list of your contacts.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'address book list',
    defaultSize: { width: 680, height: 450 },
    permissionsRequired: [],
  },
  {
    id: 'aegis-threatscope',
    type: 'MICRO_APP',
    name: 'Aegis ThreatScope',
    author: 'ΛΞVON OS',
    description: 'A real-time threat feed and alert dashboard for the Aegis subsystem, providing constant vigilance over your digital domain.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'radar security shield',
    defaultSize: { width: 380, height: 450 },
    permissionsRequired: [],
  },
  {
    id: 'aegis-command',
    type: 'MICRO_APP',
    name: 'Aegis Command',
    author: 'ΛΞVON OS',
    description: 'Configure threat intelligence feeds and manage security baselines for the Aegis subsystem.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'shield gear settings',
    defaultSize: { width: 380, height: 350 },
    permissionsRequired: ['ADMIN'],
  },
  {
    id: 'usage-monitor',
    type: 'MICRO_APP',
    name: 'Usage Monitor',
    author: 'ΛΞVON OS',
    description: 'Track your monthly Agent Action consumption against your plan limits. The core value metric.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'gauge chart data',
    defaultSize: { width: 400, height: 600 },
    permissionsRequired: [],
  },
  {
    id: 'validator',
    type: 'MICRO_APP',
    name: 'Uncut Truth Engine',
    author: 'Aegis Subsystems',
    description: "Verifies the SHA256 integrity hash of a file. The hash doesn't lie.",
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fingerprint document hash',
    defaultSize: { width: 400, height: 480 },
    permissionsRequired: [],
    tags: ['core', 'utility', 'security'],
  },
  {
    id: 'oracle-of-delphi-valley',
    type: 'MICRO_APP',
    name: 'Oracle of Delphi (Valley)',
    author: 'Klepsydra Engine',
    description: 'The Folly of Venture Capital, gamified. Make your tribute to the Oracle.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'temple oracle valley',
    defaultSize: { width: 360, height: 520 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'sisyphus-ascent',
    type: 'MICRO_APP',
    name: "Sisyphus's Ascent",
    author: 'Klepsydra Engine',
    description: 'Defy existential dread for a chance at a moment of reprieve.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'boulder mountain greek',
    defaultSize: { width: 360, height: 520 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'merchant-of-cabbage',
    type: 'MICRO_APP',
    name: 'Merchant of Cabbage',
    author: 'Klepsydra Engine',
    description: 'Protect your cabbage cart from the chaos of the Roman Forum. A high-stakes game of anachronistic commerce.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cabbage cart market',
    defaultSize: { width: 360, height: 520 },
    permissionsRequired: [],
    isFeatured: true,
  },
   {
    id: 'obelisk-marketplace',
    type: 'MICRO_APP',
    name: 'Obelisk Marketplace',
    author: 'The Pantheon',
    description: 'Transmute ΞCredits into real-world assets of power. For high-sovereignty users only.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'obelisk marble gold',
    defaultSize: { width: 600, height: 500 },
    permissionsRequired: ['OWNER_ONLY'],
    tags: ["economy", "sovereignty", "premium"]
  },
  {
    id: 'proxy-agent',
    type: 'MICRO_APP',
    name: "Proxy.Agent",
    author: 'The Pantheon',
    description: 'The transmutation layer. Authorize real-world tributes using your ΞCredit balance. Summoned, not launched.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sigil payment command',
    defaultSize: { width: 380, height: 450 },
    permissionsRequired: ['OWNER_ONLY'],
    tags: ["economy", "sovereignty", "ritual"]
  },
  {
    id: 'howards-sidekick',
    type: 'MICRO_APP',
    name: "Howard's Sidekick",
    author: "For Dustin",
    description: "A loyal electrician's sidekick for reminders, notes, and tools. Inspired by the best boy, Howard.",
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dog electrician tools',
    defaultSize: { width: 380, height: 600 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'armory',
    type: 'MICRO_APP',
    name: 'The Armory',
    author: 'ΛΞVON OS',
    description: 'A catalog of available micro-apps and tools.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sword shield forge',
    defaultSize: { width: 800, height: 600 },
    permissionsRequired: [],
  },
  {
    id: 'spectre-intelligence-suite',
    type: 'MICRO_APP',
    name: 'Spectre Intelligence Suite',
    author: 'Bloodhound Protocol // Forged by ΛΞVON OS',
    description: 'A multi-agent digital investigation console. Execute full-spectrum intelligence gathering via LangGraph daemons, OSINT reconnaissance, and synthesized dossier generation. Deploy the Burn Bridge Protocol to unleash an automated swarm of data extraction tools. Results are rendered as secure, exportable artifacts—ready for legal review or shadow operations.',
    creditCost: 999,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'private eye dossier',
    isFeatured: true,
    tags: ["intelligence", "osint", "artifact", "swarm-ai", "langgraph", "groq", "investigation", "premium"],
    branding: {
      poweredBy: ["Groq", "Swarm AI"],
      forgedIn: "ΛΞVON OS",
      callsign: "Bloodhound",
      doctrine: "Burn Bridge Protocol"
    },
    defaultSize: { width: 380, height: 600 },
    permissionsRequired: [],
  },
  {
    id: 'reno-mode',
    type: 'MICRO_APP',
    name: 'Reno Mode™',
    author: 'Dirty Beast Industries',
    description: 'You dirty, filthy beast... let’s make you purr again. The shame-neutralizing car care companion.',
    creditCost: 100,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'car wash soap',
    defaultSize: { width: 400, height: 600 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'patrickt-app',
    type: 'MICRO_APP',
    name: 'Patrickt™',
    author: 'A Sane Person',
    description: 'The Martyr of Mayhem Micro-App. Selling drugs, fucking friends, breaking hearts—and still somehow surviving your shit.',
    creditCost: 69,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'broken heart chaos',
    defaultSize: { width: 380, height: 620 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'dr-syntax',
    type: 'MICRO_APP',
    name: 'Dr. Syntax',
    author: 'ΛΞVON OS',
    description: "Sarcastic, aggressive, and borderline insulting critiques of your prompts, code, or copy. It's harsh, but it works.",
    creditCost: 200,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'scalpel pen document',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'beep-wingman',
    type: 'MICRO_APP',
    name: 'BEEP Wingman',
    author: 'ΛΞVON OS',
    description: "He's not your assistant. He's your closer. Crafts the perfect message for any tricky social situation.",
    creditCost: 120,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cockpit heart neon',
    defaultSize: { width: 360, height: 620 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'kendra',
    type: 'MICRO_APP',
    name: 'KENDRA.exe',
    author: 'The Algorithm',
    description: 'Kendall Roy’s delusion. Kris Jenner’s strategy. Your unhinged marketing agent. This is branding with beef.',
    creditCost: 99,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fashion high-heels neon',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'lahey-surveillance',
    type: 'MICRO_APP',
    name: 'Lahey Surveillance',
    author: 'Sunnyvale Security',
    description: 'I am the liquor. And I am watching. Keep an eye on employee productivity with the Shitstorm Index™.',
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'surveillance camera bottle',
    defaultSize: { width: 400, height: 500 },
    permissionsRequired: ['ADMIN'],
    isFeatured: true,
  },
  {
    id: 'kif-kroker',
    type: 'MICRO_APP',
    name: 'The Kif Kroker',
    author: 'DOOP',
    description: "*Sigh*. The team's conflict metrics are escalating again. Monitors Slack for passive-aggression and burnout.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'alien defeated sad',
    defaultSize: { width: 320, height: 420 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'lucille-bluth',
    type: 'MICRO_APP',
    name: 'The Lucille Bluth',
    author: 'Bluth Company',
    description: "Judgmental budgeting for your allowance. It's one banana, Michael. What could it cost, ten dollars?",
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'martini glass eye',
    defaultSize: { width: 320, height: 350 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'project-lumbergh',
    type: 'MICRO_APP',
    name: 'Project Lumbergh',
    author: 'Initech',
    description: "Yeeeeah, about those meetings... Analyzes invites for pointlessness and generates passive-aggressive decline memos.",
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'red stapler office',
    defaultSize: { width: 320, height: 400 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'winston-wolfe',
    type: 'MICRO_APP',
    name: 'The Winston Wolfe',
    author: 'The Fixer',
    description: "Bad review? Thirty minutes away. I'll be there in ten. Solves online reputation problems with surgical precision.",
    creditCost: 300,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sharp suit cleaning',
    defaultSize: { width: 320, height: 380 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'rolodex',
    type: 'MICRO_APP',
    name: 'The Rolodex',
    author: 'Sterling Cooper',
    description: "Analyzes new or existing contacts against a job description to determine fit and generate outreach assets.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'vintage rolodex office',
    defaultSize: { width: 320, height: 500 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'jroc-business-kit',
    type: 'MICRO_APP',
    name: "J-ROC'S BIZ KIT™",
    author: 'Roc Pile Inc.',
    description: "Get dat cheddar legit, my dawg. Generates a business name, tagline, and logo concept for your new hustle.",
    creditCost: 150,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'boombox graffiti microphone',
    defaultSize: { width: 320, height: 500 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'foremanator',
    type: 'MICRO_APP',
    name: 'The Foremanator',
    author: 'SiteCommand',
    description: 'He doesn’t sleep. He doesn’t eat. He just yells about deadlines. Processes construction site logs.',
    creditCost: 200,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hard hat construction',
    defaultSize: { width: 340, height: 500 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'sterileish',
    type: 'MICRO_APP',
    name: 'STERILE-ish™',
    author: 'Basically Compliant LLC',
    description: 'We’re basically compliant. An irreverent vibe-checker for ISO 13485, FDA, and other cleanroom logs.',
    creditCost: 500,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cleanroom laboratory science',
    defaultSize: { width: 340, height: 500 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'paper-trail',
    type: 'MICRO_APP',
    name: 'Paper Trail P.I.',
    author: 'The Agency',
    description: "The receipts don't lie. A noir detective that scans your expense receipts and gives you the 'leads'.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'detective office noir',
    defaultSize: { width: 340, height: 500 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'vandelay',
    type: 'MICRO_APP',
    name: 'Vandelay Industries',
    author: 'Art Vandelay',
    description: 'Importing, exporting, and ghosting. Generates impeccably boring, jargon-filled calendar invites to block off your time.',
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'latex architecture design',
    defaultSize: { width: 320, height: 380 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'auditor-generalissimo',
    type: 'MICRO_APP',
    name: 'The Auditor Generalissimo™',
    author: 'The State',
    description: '“Welcome to your books, comrade. You are guilty until proven solvent.” Audits finances with oppressive precision.',
    creditCost: 250,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dossier stamp military',
    defaultSize: { width: 360, height: 600 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'vin-diesel',
    type: 'MICRO_APP',
    name: 'VIN Diesel',
    author: 'The Family',
    description: 'Turbocharged compliance. For family. Validates Vehicle Identification Numbers with speed and swagger.',
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'muscle car tire',
    defaultSize: { width: 320, height: 400 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'pam-poovey-onboarding',
    type: 'MICRO_APP',
    name: 'Pam Poovey: Un-HR',
    author: 'HR (Questionable)',
    description: "Sarcastic, cynical, and vaguely unhelpful HR scripts and audio. For when you're fresh out of... you know.",
    creditCost: 70,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hr office mess',
    defaultSize: { width: 320, height: 350 },
    permissionsRequired: [],
    isFeatured: false,
  },
  {
    id: 'barbara',
    type: 'MICRO_APP',
    name: 'Agent Barbara™',
    author: 'The Bureau',
    description: "The admin daemon you never knew you needed. She detects paperwork issues before they occur. She does not ask for thanks.",
    creditCost: 350,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'paperwork compliance government',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: [],
    isFeatured: true,
  },
  {
    id: 'stonks-bot',
    type: 'MICRO_APP',
    name: 'Stonks Bot 9000',
    author: 'WallStreetBets',
    description: 'For when you need financial advice that feels more like a dare. To the moon!',
    creditCost: 10,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'diamond hands rocket',
    defaultSize: { width: 340, height: 480 },
    permissionsRequired: [],
    isFeatured: true,
  },
  // --- CHAOS CARDS ---
  {
    id: 'GEOLOGIC_TIME',
    type: 'CHAOS_CARD',
    name: 'Geologic Time',
    description: 'Feel the weight of eons in every action. A reminder that patience is a form of power.',
    cardClass: 'AESTHETIC',
    creditCost: 50,
    priceModel: 'tribute',
    rarity: 'COMMON',
    systemEffect: 'For 60 seconds, UI animations and refresh rates slow dramatically.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'slow motion clock',
    durationMinutes: 1,
  },
  {
    id: 'ACROPOLIS_MARBLE',
    type: 'CHAOS_CARD',
    name: 'Acropolis Marble',
    description: 'Re-skin your digital architecture in the stone of the ancients. Clean, classical, eternal.',
    cardClass: 'AESTHETIC',
    creditCost: 75,
    priceModel: 'tribute',
    rarity: 'COMMON',
    systemEffect: 'Applies a `theme-acropolis-marble` class to the root element, rendering the UI in stark whites and greys with golden accents for one hour.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'marble statue',
    durationMinutes: 60,
  },
  {
    id: 'NOCTUAS_GAZE',
    type: 'CHAOS_CARD',
    name: "Noctua's Gaze",
    description: "Adopt the vision of Athena's owl. See clarity in the darkness.",
    cardClass: 'AESTHETIC',
    creditCost: 75,
    priceModel: 'tribute',
    rarity: 'COMMON',
    systemEffect: "Activates a pure black 'dark mode' with silver text.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'owl eyes',
    durationMinutes: 60,
  },
  {
    id: 'FRACTAL_BLOOM',
    type: 'CHAOS_CARD',
    name: 'Fractal Bloom',
    description: "The universe's geometry, revealed in a flash. The math of nature, made manifest.",
    cardClass: 'AESTHETIC',
    creditCost: 100,
    priceModel: 'tribute',
    rarity: 'COMMON',
    systemEffect: 'Every action spawns a temporary, intricate fractal pattern.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'fractal pattern',
  },
  {
    id: 'WEEPING_GLASS',
    type: 'CHAOS_CARD',
    name: 'Weeping Glass',
    description: 'For a short time, the hard edges of your OS soften and flow. A reminder that even structure is fluid.',
    cardClass: 'AESTHETIC',
    creditCost: 50,
    priceModel: 'tribute',
    rarity: 'COMMON',
    systemEffect: 'For 15 minutes, a `theme-weeping-glass` class is applied, causing UI elements on the Canvas to develop a slow, "dripping" animation.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'liquid glass',
    durationMinutes: 15,
  },
  {
    id: 'ORACLES_DECREE',
    type: 'CHAOS_CARD',
    name: "Oracle's Decree",
    description: 'The Pythia speaks through the machine. Your next security alert arrives as prophecy. Interpret it wisely.',
    cardClass: 'AGENTIC',
    creditCost: 175,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    systemEffect: 'The next security alert from Aegis is delivered in cryptic, prophetic dactylic hexameter.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'oracle prophecy',
  },
  {
    id: 'BIOMIMICRY',
    type: 'CHAOS_CARD',
    name: 'Biomimicry',
    description: 'Ask your agent to look to nature for the answer. The oldest solutions are the most elegant.',
    cardClass: 'AGENTIC',
    creditCost: 250,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    systemEffect: "An agent re-designs a targeted workflow's logic based on a principle from nature.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'nature pattern',
  },
  {
    id: 'SOCRATIC_METHOD',
    type: 'CHAOS_CARD',
    name: 'Socratic Method',
    description: 'Your agent will no longer give you answers, only questions. True knowledge is born from inquiry.',
    cardClass: 'AGENTIC',
    creditCost: 200,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    systemEffect: 'For 5 minutes, agentic suggestions are replaced with probing questions.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'question mark',
  },
  {
    id: 'THESPIAN_MASK',
    type: 'CHAOS_CARD',
    name: 'Thespian Mask',
    description: 'An agent may play many parts. Assign the masks of Comedy and Tragedy.',
    cardClass: 'AGENTIC',
    creditCost: 200,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    systemEffect: 'For 10 minutes, BEEP adopts a tragic persona, while Aegis communicates with comedic optimism.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'theater masks',
    durationMinutes: 10,
  },
  {
    id: 'BEEPS_CYNICISM',
    type: 'CHAOS_CARD',
    name: "BEEP's Cynicism",
    description: 'Unleash the spirit of Diogenes. For when you need commentary that bites through all pretense.',
    cardClass: 'AGENTIC',
    creditCost: 150,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    systemEffect: "For the next 5 interactions, BEEP's responses become brutally honest and cynical.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'robot smirk',
  },
  {
    id: 'GORDIAN_KNOT',
    type: 'CHAOS_CARD',
    name: 'Gordian Knot',
    description: "Some problems aren't meant to be solved. They're meant to be severed. Act decisively.",
    cardClass: 'SYSTEMIC',
    creditCost: 400,
    priceModel: 'tribute',
    rarity: 'RARE',
    systemEffect: 'A hopelessly scrambled workflow appears. Solve it in 90 seconds for a massive bonus.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'tangled knot',
  },
  {
    id: 'SUDDEN_ECLIPSE',
    type: 'CHAOS_CARD',
    name: 'Sudden Eclipse',
    description: 'The sky darkens without warning. Only those with inner vision can navigate the sudden night.',
    cardClass: 'SYSTEMIC',
    creditCost: 450,
    priceModel: 'tribute',
    rarity: 'RARE',
    systemEffect: 'For 2 minutes, your Canvas goes almost completely black, with only small pools of light around your cursor.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'solar eclipse',
  },
  {
    id: 'THE_RIVER_LETHE',
    type: 'CHAOS_CARD',
    name: 'The River Lethe',
    description: 'Dip your OS in the river of forgetfulness. A clean slate is both a risk and an opportunity.',
    cardClass: 'SYSTEMIC',
    creditCost: 350,
    priceModel: 'tribute',
    rarity: 'RARE',
    systemEffect: 'Your OS command history and cache are wiped clean. Predictive assistance is temporarily gone.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'river memory',
  },
  {
    id: 'LABYRINTHINE_SHIFT',
    type: 'CHAOS_CARD',
    name: 'Labyrinthine Shift',
    description: 'The Minotaur is doubt. The maze is your own mind. Do not get lost.',
    cardClass: 'SYSTEMIC',
    creditCost: 350,
    priceModel: 'tribute',
    rarity: 'RARE',
    systemEffect: 'Your Canvas reconfigures into a maze-like structure of overlapping windows and panels.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'maze labyrinth',
  },
  {
    id: 'KRONOSS_GIFT',
    type: 'CHAOS_CARD',
    name: "Kronos's Gift",
    description: 'Seize control of time itself. For a moment, you are the Titan.',
    cardClass: 'SYSTEMIC',
    creditCost: 600,
    priceModel: 'tribute',
    rarity: 'MYTHIC',
    systemEffect: 'For 45 seconds, you gain a "time scrub" bar, allowing you to rewind the last 10 seconds of your OS activity.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'time clock',
  },
  {
    id: 'LAMBDAS_PHALANX',
    type: 'CHAOS_CARD',
    name: "Lambda's Phalanx (Λ)",
    description: 'One shield protects another. Link your agents into an unbreakable spearpoint.',
    cardClass: 'SYNDICATE',
    creditCost: 800,
    priceModel: 'tribute',
    rarity: 'MYTHIC',
    systemEffect: 'For 10 minutes, all Syndicate members can volunteer agentic processing power to one chosen member.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'spartan phalanx',
  },
  {
    id: 'MYCELIAL_NETWORK',
    type: 'CHAOS_CARD',
    name: 'Mycelial Network',
    description: 'Beneath the forest floor, all are connected. Share the harvest of the digital soil.',
    cardClass: 'SYNDICATE',
    creditCost: 500,
    priceModel: 'tribute',
    rarity: 'RARE',
    systemEffect: 'For the next hour, 10% of all ΞCredits earned by each Syndicate member are pooled and then divided equally.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'mushroom network',
  },
  {
    id: 'OSTRACIZE',
    type: 'CHAOS_CARD',
    name: 'Ostracize',
    description: 'The Polis is sacred. A threat to its harmony must be... temporarily isolated. A vote is called.',
    cardClass: 'SYNDICATE',
    creditCost: 1000,
    priceModel: 'tribute',
    rarity: 'MYTHIC',
    systemEffect: 'Your Syndicate can vote to place a "Shard of Exile" on any user, preventing them from playing Chaos Cards for 24 hours.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'broken pottery',
  },
  {
    id: 'WHISPERED_CHALLENGE',
    type: 'CHAOS_CARD',
    name: 'Whispered Challenge',
    description: 'A duel, fought in lines of code and silent automation. Issue a challenge from the shadows.',
    cardClass: 'SYNDICATE',
    creditCost: 250,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    systemEffect: 'Secretly challenge a rival user based on a defined metric. The winner receives the wagered ΞCredits.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'duel glove',
  },
  {
    id: 'ROSETTA_STONE',
    type: 'CHAOS_CARD',
    name: 'Rosetta Stone',
    description: 'Some languages are impossible for one mind to translate. But together, you can decipher the code.',
    cardClass: 'SYNDICATE',
    creditCost: 1200,
    priceModel: 'tribute',
    rarity: 'MYTHIC',
    systemEffect: 'Provides a critical clue to a member\'s "Glitch in the Glass," delivered in fragments to different Syndicate members.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'stone tablet',
  },
  // --- RITUAL BOONS (MERCENARY CARDS) ---
  {
    id: 'LOADED_DIE',
    type: 'CHAOS_CARD',
    name: 'Loaded Die',
    description: 'Subtly bend the laws of probability. Grants a slight, invisible buff to your next 3 tributes.',
    cardClass: 'BOON',
    creditCost: 250,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'glowing dice',
  },
  {
    id: 'SISYPHUS_REPRIEVE',
    type: 'CHAOS_CARD',
    name: "Sisyphus's Reprieve",
    description: 'Even the gods show mercy, sometimes. Guarantees your next tribute to Sisyphus will not result in a loss.',
    cardClass: 'BOON',
    creditCost: 150,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'boulder resting',
  },
  {
    id: 'ORACLES_INSIGHT',
    type: 'CHAOS_CARD',
    name: "Oracle's Insight",
    description: 'For a brief time, the Oracle reveals the true payout probabilities, letting you see the hidden machinery of fate.',
    cardClass: 'BOON',
    creditCost: 500,
    priceModel: 'tribute',
    rarity: 'RARE',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'glowing eye chart',
  },
  {
    id: 'HADES_BARGAIN',
    type: 'CHAOS_CARD',
    name: "Hades' Bargain",
    description: 'A pact with the underworld. Doubles your next tribute, for double the potential boon... or double the fall.',
    cardClass: 'BOON',
    creditCost: 100,
    priceModel: 'tribute',
    rarity: 'UNCOMMON',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'skull coin',
  },
];
