
export type ChaosCardManifest = {
  key: string;
  name: string;
  description: string;
  cardClass: 'AESTHETIC' | 'AGENTIC' | 'SYSTEMIC' | 'SYNDICATE';
  cost: number;
  systemEffect: string;
  imageUrl: string;
  imageHint: string;
};

export const chaosCardManifest: ChaosCardManifest[] = [
  // Class I: Aesthetic Aberrations
  {
    key: 'WEEPING_GLASS',
    name: 'Weeping Glass',
    description: 'For a short time, the hard edges of your OS soften and flow. A reminder that even structure is fluid.',
    cardClass: 'AESTHETIC',
    cost: 50,
    systemEffect: 'For 15 minutes, UI elements on the Canvas develop a slow, "dripping" animation.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'liquid glass dripping',
  },
  {
    key: 'ANCESTRAL_FONT',
    name: 'Ancestral Font',
    description: 'Words carry weight. Make yours feel ancient.',
    cardClass: 'AESTHETIC',
    cost: 50,
    systemEffect: 'All header text in the OS renders in a custom, elegant, runic-style font for one hour.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'rune stone ancient',
  },
  {
    key: 'GLITCH_BLOOM',
    name: 'Glitch Bloom',
    description: 'A flaw, cultivated into a feature. A moment of imperfection, perfected.',
    cardClass: 'AESTHETIC',
    cost: 75,
    systemEffect: 'For 5 minutes, every click or agent action spawns a tiny, harmless, yet beautiful fractal glitch that blooms and fades.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'fractal glitch digital',
  },
  {
    key: 'AUDITORY_MIRAGE',
    name: 'Auditory Mirage',
    description: 'Change the sound of silence. Change the echo of action.',
    cardClass: 'AESTHETIC',
    cost: 75,
    systemEffect: 'Replaces all standard OS notification sounds with subtle, atmospheric alternatives for 3 hours.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'sound wave abstract',
  },
  {
    key: 'COLOR_INVERSE',
    name: 'Color Inverse',
    description: 'See your world through a different lens. A new perspective is only a shade away.',
    cardClass: 'AESTHETIC',
    cost: 100,
    systemEffect: 'Inverts the primary and secondary colors of your UI theme for 30 minutes.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'negative photo color wheel',
  },
  {
    key: 'PARALLAX_SHIFT',
    name: 'Parallax Shift',
    description: 'Adds depth to the glass. Makes your Canvas feel infinite.',
    cardClass: 'AESTHETIC',
    cost: 100,
    systemEffect: 'Activates a subtle parallax effect on your Canvas.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'layers depth abstract',
  },
  // Class II: Agentic Whims
  {
    key: 'BEEPS_SARCASM_CASCADE',
    name: "BEEP's Sarcasm Cascade",
    description: 'Unleash your snarkiest agent. For when you need ruthless efficiency with a side of biting commentary.',
    cardClass: 'AGENTIC',
    cost: 150,
    systemEffect: "For the next 5 interactions, BEEP's responses become hyper-sarcastic.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'robot laughing smirk',
  },
  {
    key: 'AEGISS_PARABLE',
    name: "Aegis's Parable",
    description: "Security doesn't have to be sterile. Let your guardian speak in tongues of wisdom and warning.",
    cardClass: 'AGENTIC',
    cost: 175,
    systemEffect: 'The next 3 security alerts from Aegis are delivered as cryptic, philosophical parables.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'shield scroll ancient',
  },
  {
    key: 'AGENT_SWAP',
    name: 'Agent Swap',
    description: 'A change in voice can change everything. Who is really running the show?',
    cardClass: 'AGENTIC',
    cost: 200,
    systemEffect: 'For 10 minutes, your agents swap personalities.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'two faces abstract',
  },
  {
    key: 'PREDICTIVE_WHISPER',
    name: 'Predictive Whisper',
    description: 'Your agent becomes prescient, whispering its next move before it acts.',
    cardClass: 'AGENTIC',
    cost: 225,
    systemEffect: "For 5 minutes, your primary agent's next suggested action appears as a faint, ghostly text overlay.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'ghostly text whisper',
  },
  {
    key: 'WORKFLOW_IMPROVISATION',
    name: 'Workflow Improvisation',
    description: 'Introduce a single, random variable into your most stable process. True mastery is adaptation.',
    cardClass: 'AGENTIC',
    cost: 250,
    systemEffect: 'Target one workflow. The agent will add one unnecessary, but harmless and creative, step to its next execution.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'jazz music abstract',
  },
  {
    key: 'SILENT_TREATMENT',
    name: 'Silent Treatment',
    description: 'For when you want pure, uninterrupted flow. The agents will do their work, but they will not speak unless spoken to.',
    cardClass: 'AGENTIC',
    cost: 250,
    systemEffect: 'Activates "Silent Mode" for one hour. All agent vocalizations and proactive pop-ups cease.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'zen garden silent',
  },
  // Class III: Systemic Tremors
  {
    key: 'ROGUE_SINGULARITY',
    name: 'Rogue Singularity',
    description: "A puzzle box from the void. What's inside is valuable, if you have the key. And the nerve.",
    cardClass: 'SYSTEMIC',
    cost: 400,
    systemEffect: 'A mysterious, encrypted data object appears. Crack it in 3 minutes for a 1000 Ξ bonus.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'puzzle box mystery',
  },
  {
    key: 'XCREDIT_RUSH',
    name: 'ΞCredit Rush',
    description: 'Gamble your flow state. Bet that you can achieve brilliance on command.',
    cardClass: 'SYSTEMIC',
    cost: 500,
    systemEffect: 'Instantly triggers a 90-second ΞRush event (pulsing UI, double credit rewards).',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'gold coins rush',
  },
  {
    key: 'CANVAS_SCRAMBLE',
    name: 'Canvas Scramble',
    description: 'Chaos is a ladder. Can you climb it if the rungs keep moving?',
    cardClass: 'SYSTEMIC',
    cost: 350,
    systemEffect: 'For 60 seconds, your Micro-App windows on the Canvas slowly drift and rearrange themselves.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'chaos abstract scramble',
  },
  {
    key: 'TIME_DILATION',
    name: 'Time Dilation',
    description: 'Slow the world down. Or speed it up. For a moment, you are the master of the clock.',
    cardClass: 'SYSTEMIC',
    cost: 600,
    systemEffect: 'Choose one: For 30 seconds, all animations run at 50% speed OR at 200% speed.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'clock melting abstract',
  },
  {
    key: 'RESOURCE_DROUGHT',
    name: 'Resource Drought',
    description: 'Force your agents to become more efficient. Starve them, and watch them innovate.',
    cardClass: 'SYSTEMIC',
    cost: 300,
    systemEffect: "For 10 minutes, your agents' processing power is 'throttled' by 25%.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'desert cracked efficiency',
  },
  // Class IV: Syndicate Invocations
  {
    key: 'WHISPERED_CHALLENGE',
    name: 'Whispered Challenge',
    description: 'A duel, fought in lines of code and silent automation. Issue a challenge from the shadows.',
    cardClass: 'SYNDICATE',
    cost: 250,
    systemEffect: 'Secretly challenge a rival Syndicate member to an automation duel.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'duel glove challenge',
  },
  {
    key: 'SHARED_VISION',
    name: 'Shared Vision',
    description: 'Synchronize the aesthetic of your entire Syndicate. One mind, one design.',
    cardClass: 'SYNDICATE',
    cost: 750,
    systemEffect: 'For 24 hours, all members of your Syndicate share your UI theme.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'teamwork abstract vision',
  },
  {
    key: 'NEMESIS_HINT',
    name: 'Nemesis Hint',
    description: 'Every Glitch has a weakness. For a price, your Syndicate can buy a clue.',
    cardClass: 'SYNDICATE',
    cost: 1000,
    systemEffect: "Deliver a cryptic clue to the entire Syndicate on how to defeat a specific Nemesis.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'mystery clue secret',
  },
];
