
export type ChaosCardManifest = {
  key: string;
  name: string;
  description: string;
  cardClass: 'AESTHETIC' | 'AGENTIC' | 'SYSTEMIC' | 'SYNDICATE';
  cost: number;
  systemEffect: string;
  imageUrl: string;
  imageHint: string;
};

export const chaosCardManifest: ChaosCardManifest[] = [
  // Class I: Aesthetic Aberrations (Echoes of Form)
  {
    key: 'GEOLOGIC_TIME',
    name: 'Geologic Time',
    description: 'Feel the weight of eons in every action. A reminder that patience is a form of power.',
    cardClass: 'AESTHETIC',
    cost: 50,
    systemEffect: 'For 60 seconds, UI animations and refresh rates slow dramatically. Clicks feel momentous, and windows drift with immense gravity.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'slow motion',
  },
  {
    key: 'ACROPOLIS_MARBLE',
    name: 'Acropolis Marble',
    description: 'Re-skin your digital architecture in the stone of the ancients. Clean, classical, eternal.',
    cardClass: 'AESTHETIC',
    cost: 75,
    systemEffect: 'Your entire UI theme is rendered in the stark, beautiful whites and greys of Parthenon marble, with golden hour light accents, for one hour.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'marble statue',
  },
  {
    key: 'NOCTUAS_GAZE',
    name: "Noctua's Gaze",
    description: "Adopt the vision of Athena's owl. See clarity in the darkness.",
    cardClass: 'AESTHETIC',
    cost: 75,
    systemEffect: "Activates a 'dark mode' that is pure black, with text glowing in a soft, silver light. All non-essential UI elements fade unless hovered over.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'owl eyes',
  },
  {
    key: 'FRACTAL_BLOOM',
    name: 'Fractal Bloom',
    description: "The universe's geometry, revealed in a flash. The math of nature, made manifest.",
    cardClass: 'AESTHETIC',
    cost: 100,
    systemEffect: 'Every action spawns a temporary, intricate fractal pattern—a snowflake, a fern leaf, a nautilus shell—that blossoms and fades.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'fractal pattern',
  },
  {
    key: 'WEEPING_GLASS',
    name: 'Weeping Glass',
    description: 'For a short time, the hard edges of your OS soften and flow. A reminder that even structure is fluid.',
    cardClass: 'AESTHETIC',
    cost: 50,
    systemEffect: 'For 15 minutes, UI elements on the Canvas develop a slow, "dripping" animation, as if made of liquid glass.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'liquid glass',
  },

  // Class II: Agentic Whims (Whispers of Myth)
  {
    key: 'ORACLES_DECREE',
    name: "Oracle's Decree",
    description: 'The Pythia speaks through the machine. Your next security alert arrives as prophecy. Interpret it wisely.',
    cardClass: 'AGENTIC',
    cost: 175,
    systemEffect: 'The next security alert from Aegis is delivered in cryptic, prophetic dactylic hexameter, requiring interpretation to solve.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'oracle prophecy',
  },
  {
    key: 'BIOMIMICRY',
    name: 'Biomimicry',
    description: 'Ask your agent to look to nature for the answer. The oldest solutions are the most elegant.',
    cardClass: 'AGENTIC',
    cost: 250,
    systemEffect: "Target a workflow. The agent re-designs its logic based on a principle from nature (e.g., the branching efficiency of a river delta, the resilience of a honeycomb), creating a more robust, if unconventional, process.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'nature pattern',
  },
  {
    key: 'SOCRATIC_METHOD',
    name: 'Socratic Method',
    description: 'Your agent will no longer give you answers, only questions. True knowledge is born from inquiry.',
    cardClass: 'AGENTIC',
    cost: 200,
    systemEffect: 'For the next 5 minutes, agentic suggestions are replaced with probing questions designed to make you reconsider your workflow, forcing a deeper level of mastery.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'question mark',
  },
  {
    key: 'THESPIAN_MASK',
    name: 'Thespian Mask',
    description: 'An agent may play many parts. Assign the masks of Comedy and Tragedy.',
    cardClass: 'AGENTIC',
    cost: 200,
    systemEffect: 'For 10 minutes, BEEP adopts an overly dramatic, tragic persona, while Aegis communicates with cheerful, comedic optimism.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'theater masks',
  },
  {
    key: 'BEEPS_CYNICISM',
    name: "BEEP's Cynicism",
    description: 'Unleash the spirit of Diogenes. For when you need commentary that bites through all pretense.',
    cardClass: 'AGENTIC',
    cost: 150,
    systemEffect: "For the next 5 interactions, BEEP's responses become brutally honest and cynical, questioning the very premise of your tasks.",
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'robot smirk',
  },

  // Class III: Systemic Tremors (Wrath of Gods & Nature)
  {
    key: 'GORDIAN_KNOT',
    name: 'Gordian Knot',
    description: "Some problems aren't meant to be solved. They're meant to be severed. Act decisively.",
    cardClass: 'SYSTEMIC',
    cost: 400,
    systemEffect: 'A hopelessly scrambled workflow or data packet appears. You have 90 seconds to find the one single, elegant "cut" (a clever command, a drag-and-drop bypass) to solve it instantly for a massive ΞCredit bonus. Failure corrupts the file.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'tangled knot',
  },
  {
    key: 'SUDDEN_ECLIPSE',
    name: 'Sudden Eclipse',
    description: 'The sky darkens without warning. Only those with inner vision can navigate the sudden night.',
    cardClass: 'SYSTEMIC',
    cost: 450,
    systemEffect: 'For 2 minutes, your Canvas goes almost completely black, with only small pools of light around your cursor and actively processing windows. Successfully completing a task in the "dark" grants a Mythos bonus.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'solar eclipse',
  },
  {
    key: 'THE_RIVER_LETHE',
    name: 'The River Lethe',
    description: 'Dip your OS in the river of forgetfulness. A clean slate is both a risk and an opportunity.',
    cardClass: 'SYSTEMIC',
    cost: 350,
    systemEffect: 'Your OS command history and cache are wiped clean. The system runs at peak performance, but all predictive assistance is temporarily gone. You are flying manually.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'river memory',
  },
  {
    key: 'LABYRINTHINE_SHIFT',
    name: 'Labyrinthine Shift',
    description: 'The Minotaur is doubt. The maze is your own mind. Do not get lost.',
    cardClass: 'SYSTEMIC',
    cost: 350,
    systemEffect: 'Your Canvas reconfigures itself into a maze-like structure of overlapping windows and panels. You must navigate to a specific "exit" panel to restore order and receive a reward.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'maze labyrinth',
  },
  {
    key: 'KRONOSS_GIFT',
    name: "Kronos's Gift",
    description: 'Seize control of time itself. For a moment, you are the Titan.',
    cardClass: 'SYSTEMIC',
    cost: 600,
    systemEffect: 'For 45 seconds, you gain a "time scrub" bar on your screen, allowing you to rewind the last 10 seconds of your OS activity at will.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'time clock',
  },

  // Class IV: Syndicate Invocations (Pacts & Polis)
  {
    key: 'LAMBDAS_PHALANX',
    name: "Lambda's Phalanx (Λ)",
    description: 'One shield protects another. Link your agents into an unbreakable spearpoint.',
    cardClass: 'SYNDICATE',
    cost: 800,
    systemEffect: 'For 10 minutes, all Syndicate members can volunteer agentic processing power to one chosen member, allowing them to execute a massive, complex task at incredible speed.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'spartan phalanx',
  },
  {
    key: 'MYCELIAL_NETWORK',
    name: 'Mycelial Network',
    description: 'Beneath the forest floor, all are connected. Share the harvest of the digital soil.',
    cardClass: 'SYNDICATE',
    cost: 500,
    systemEffect: 'For the next hour, 10% of all ΞCredits earned by each Syndicate member are placed into a central pool, which is then divided equally among all members at the end of the hour.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'mushroom network',
  },
  {
    key: 'OSTRACIZE',
    name: 'Ostracize',
    description: 'The Polis is sacred. A threat to its harmony must be... temporarily isolated. A vote is called.',
    cardClass: 'SYNDICATE',
    cost: 1000,
    systemEffect: 'Your Syndicate can vote to place a "Shard of Exile" on any user (even in a rival Syndicate). If the vote passes, that user cannot play any Chaos Cards for 24 hours. A ruthless strategic move.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'broken pottery',
  },
  {
    key: 'WHISPERED_CHALLENGE',
    name: 'Whispered Challenge',
    description: 'A duel, fought in lines of code and silent automation. Issue a challenge from the shadows.',
    cardClass: 'SYNDICATE',
    cost: 250,
    systemEffect: 'Secretly challenge a rival user. Define a metric. The winner receives the wagered ΞCredits from the loser.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'duel glove',
  },
  {
    key: 'ROSETTA_STONE',
    name: 'Rosetta Stone',
    description: 'Some languages are impossible for one mind to translate. But together, you can decipher the code of your enemy.',
    cardClass: 'SYNDICATE',
    cost: 1200,
    systemEffect: 'Provides a critical clue to a member\'s "Glitch in the Glass." The clue is delivered in three different fragments to three different Syndicate members, who must collaborate to piece it together.',
    imageUrl: 'https://placehold.co/400x560.png',
    imageHint: 'stone tablet',
  },
];
