// This file serves as a non-database source of truth for micro-app manifests.
// In a larger system, this could be stored in a database and managed via an admin interface.

export type MicroAppManifest = {
  id: string;
  name: string;
  description: string;
  author: string;
  creditCost: number;
  priceModel: 'one-time' | 'subscription' | 'included';
  imageUrl: string;
  imageHint: string;
  defaultSize: { width: number; height: number };
  permissionsRequired: string[];
  routingPath: string;
  contextAwareCapabilities: string[];
  isFeatured?: boolean;
};

export const microAppManifests: MicroAppManifest[] = [
  // --- System Apps (Included) ---
  {
    id: 'file-explorer',
    name: 'File Explorer',
    author: 'ΛΞVON OS',
    description: 'Access and manage your files.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'data folders files',
    defaultSize: { width: 400, height: 300 },
    permissionsRequired: [],
    routingPath: '/file-explorer',
    contextAwareCapabilities: [],
  },
  {
    id: 'terminal',
    name: 'Terminal',
    author: 'ΛΞVON OS',
    description: 'Direct command-line access.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'code command line',
    defaultSize: { width: 450, height: 300 },
    permissionsRequired: [],
    routingPath: '/terminal',
    contextAwareCapabilities: [],
  },
  {
    id: 'admin-console',
    name: 'Admin Console',
    author: 'ΛΞVON OS',
    description: 'Manage users, monitor system health, and configure workspace settings. For Administrators only.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dashboard settings users',
    defaultSize: { width: 700, height: 550 },
    permissionsRequired: ['ADMIN'],
    routingPath: '/admin-console',
    contextAwareCapabilities: [],
  },
  {
    id: 'ai-suggestion',
    name: 'AI Suggestion',
    author: 'ΛΞVON OS',
    description: 'Click to execute this command.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'lightbulb idea',
    defaultSize: { width: 320, height: 120 },
    permissionsRequired: [],
    routingPath: '/ai-suggestion',
    contextAwareCapabilities: [],
  },
  {
    id: 'aegis-control',
    name: 'Aegis Security Report',
    author: 'ΛΞVON OS',
    description: "Analysis of the last command's security profile.",
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'security shield report',
    defaultSize: { width: 320, height: 220 },
    permissionsRequired: [],
    routingPath: '/aegis-control',
    contextAwareCapabilities: [],
  },
  {
    id: 'contact-list',
    name: 'Contact List',
    author: 'ΛΞVON OS',
    description: 'A list of your contacts.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'address book list',
    defaultSize: { width: 680, height: 450 },
    permissionsRequired: [],
    routingPath: '/contact-list',
    contextAwareCapabilities: [],
  },
  {
    id: 'contact-editor',
    name: 'Contact Editor',
    author: 'ΛΞVON OS',
    description: 'Create or update a contact.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'edit form user',
    defaultSize: { width: 320, height: 380 },
    permissionsRequired: [],
    routingPath: '/contact-editor',
    contextAwareCapabilities: [],
  },
  {
    id: 'user-profile-settings',
    name: 'User Profile',
    author: 'ΛΞVON OS',
    description: 'Manage your user profile settings.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'user settings profile',
    defaultSize: { width: 340, height: 420 },
    permissionsRequired: [],
    routingPath: '/user-profile-settings',
    contextAwareCapabilities: [],
  },
  {
    id: 'workspace-settings',
    name: 'Workspace Settings',
    author: 'ΛΞVON OS',
    description: 'Manage your workspace settings.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'workspace settings gear',
    defaultSize: { width: 340, height: 240 },
    permissionsRequired: [],
    routingPath: '/workspace-settings',
    contextAwareCapabilities: [],
  },
  {
    id: 'aegis-threatscope',
    name: 'Aegis ThreatScope',
    author: 'ΛΞVON OS',
    description: 'A real-time threat feed and alert dashboard for the Aegis subsystem, providing constant vigilance over your digital domain.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'radar security shield',
    defaultSize: { width: 380, height: 450 },
    permissionsRequired: ['read:security_alerts'],
    routingPath: '/aegis-threatscope',
    contextAwareCapabilities: ['security_alert_stream'],
    isFeatured: false,
  },
  {
    id: 'aegis-command',
    name: 'Aegis Command',
    author: 'ΛΞVON OS',
    description: 'Configure threat intelligence feeds and manage security baselines for the Aegis subsystem.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'shield gear settings',
    defaultSize: { width: 380, height: 350 },
    permissionsRequired: ['write:security_config'],
    routingPath: '/aegis-command',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'usage-monitor',
    name: 'Usage Monitor',
    author: 'ΛΞVON OS',
    description: 'Track your monthly Agent Action consumption against your plan limits. The core value metric.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'gauge chart data',
    defaultSize: { width: 400, height: 600 },
    permissionsRequired: ['read:billing'],
    routingPath: '/usage-monitor',
    contextAwareCapabilities: ['billing_update_event'],
    isFeatured: false,
  },
  {
    id: 'orphean-oracle',
    name: 'The Orphean Oracle',
    author: 'ΛΞVON OS',
    description: 'Descends into the data underworld to return with a story. A metaphorical, visual narrative of your business data.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'lyre strings data',
    defaultSize: { width: 400, height: 500 },
    permissionsRequired: ['read:business_data'],
    routingPath: '/orphean-oracle',
    contextAwareCapabilities: ['data_stream_analysis'],
    isFeatured: false,
  },
  {
    id: 'top-up',
    name: 'Top-Up Credits',
    author: 'ΛΞVON OS',
    description: 'Add ΞCredits to your workspace balance via out-of-band payment.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'coin plus payment',
    defaultSize: { width: 320, height: 400 },
    permissionsRequired: ['write:billing'],
    routingPath: '/top-up',
    contextAwareCapabilities: [],
  },
  {
    id: 'validator',
    name: 'Uncut Truth Engine',
    author: 'Aegis Subsystems',
    description: "Verifies the SHA256 integrity hash of a file. The hash doesn't lie.",
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fingerprint document hash',
    defaultSize: { width: 400, height: 480 },
    permissionsRequired: [],
    routingPath: '/validator',
    contextAwareCapabilities: [],
  },
  
  // --- Acquirable Apps (One-Time Cost) ---
  {
    id: 'armory',
    name: 'The Armory',
    author: 'ΛΞVON OS',
    description: 'A catalog of available micro-apps and tools.',
    creditCost: 0, // This is a special case, it's included but acts as the gateway to paid apps
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sword shield forge',
    defaultSize: { width: 800, height: 600 },
    permissionsRequired: [],
    routingPath: '/armory',
    contextAwareCapabilities: [],
  },
  {
    id: 'dr-syntax',
    name: 'Dr. Syntax',
    author: 'ΛΞVON OS',
    description: "Sarcastic, aggressive, and borderline insulting critiques of your prompts, code, or copy. It's harsh, but it works.",
    creditCost: 200,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'scalpel pen document',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: [],
    routingPath: '/dr-syntax',
    contextAwareCapabilities: [],
    isFeatured: true,
  },
  {
    id: 'beep-wingman',
    name: 'BEEP Wingman',
    author: 'ΛΞVON OS',
    description: "He's not your assistant. He's your closer. Crafts the perfect message for any tricky social situation.",
    creditCost: 120,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cockpit heart neon',
    defaultSize: { width: 360, height: 620 },
    permissionsRequired: [],
    routingPath: '/beep-wingman',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'kendra',
    name: 'KENDRA.exe',
    author: 'The Algorithm',
    description: 'Kendall Roy’s delusion. Kris Jenner’s strategy. Your unhinged marketing agent. This is branding with beef.',
    creditCost: 99,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fashion high-heels neon',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: [],
    routingPath: '/kendra',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'infidelity-radar',
    name: 'Infidelity Radar',
    author: 'Spectre Intelligence',
    description: 'Because intuition deserves evidence. A suite of tools for digital investigation and behavioral analysis.',
    creditCost: 500,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'private eye dossier',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: ['integration:social_media', 'read:user_activity_logs'],
    routingPath: '/infidelity-radar',
    contextAwareCapabilities: ['osint_scan_hook', 'behavioral_analysis_hook'],
    isFeatured: false,
  },
  {
    id: 'lahey-surveillance',
    name: 'Lahey Surveillance',
    author: 'Sunnyvale Security',
    description: 'I am the liquor. And I am watching. Keep an eye on employee productivity with the Shitstorm Index™.',
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'surveillance camera bottle',
    defaultSize: { width: 400, height: 500 },
    permissionsRequired: ['read:user_activity_logs'],
    routingPath: '/lahey-surveillance',
    contextAwareCapabilities: ['user_activity_stream', 'anomaly_detection_hook'],
    isFeatured: true,
  },
  {
    id: 'kif-kroker',
    name: 'The Kif Kroker',
    author: 'DOOP',
    description: "*Sigh*. The team's conflict metrics are escalating again. Monitors Slack for passive-aggression and burnout.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'alien defeated sad',
    defaultSize: { width: 320, height: 420 },
    permissionsRequired: ['integration:slack'],
    routingPath: '/kif-kroker',
    contextAwareCapabilities: ['comms_analysis_stream'],
    isFeatured: true,
  },
  {
    id: 'lucille-bluth',
    name: 'The Lucille Bluth',
    author: 'Bluth Company',
    description: "Judgmental budgeting for your allowance. It's one banana, Michael. What could it cost, ten dollars?",
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'martini glass eye',
    defaultSize: { width: 320, height: 350 },
    permissionsRequired: ['read:expenses'],
    routingPath: '/lucille-bluth',
    contextAwareCapabilities: ['expense_entry_hook'],
    isFeatured: true,
  },
  {
    id: 'project-lumbergh',
    name: 'Project Lumbergh',
    author: 'Initech',
    description: "Yeeeeah, about those meetings... Analyzes invites for pointlessness and generates passive-aggressive decline memos.",
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'red stapler office',
    defaultSize: { width: 320, height: 400 },
    permissionsRequired: ['read:calendar'],
    routingPath: '/project-lumbergh',
    contextAwareCapabilities: ['calendar_event_hook'],
    isFeatured: true,
  },
  {
    id: 'winston-wolfe',
    name: 'The Winston Wolfe',
    author: 'The Fixer',
    description: "Bad review? Thirty minutes away. I'll be there in ten. Solves online reputation problems with surgical precision.",
    creditCost: 300,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sharp suit cleaning',
    defaultSize: { width: 320, height: 380 },
    permissionsRequired: ['integration:social_media'],
    routingPath: '/winston-wolfe',
    contextAwareCapabilities: ['reputation_alert_stream'],
    isFeatured: true,
  },
  {
    id: 'rolodex',
    name: 'The Rolodex',
    author: 'Sterling Cooper',
    description: "Analyzes new or existing contacts against a job description to determine fit and generate outreach assets.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'vintage rolodex office',
    defaultSize: { width: 320, height: 500 },
    permissionsRequired: [],
    routingPath: '/rolodex',
    contextAwareCapabilities: [],
    isFeatured: true,
  },
  {
    id: 'jroc-business-kit',
    name: "J-ROC'S BIZ KIT™",
    author: 'Roc Pile Inc.',
    description: "Get dat cheddar legit, my dawg. Generates a business name, tagline, and logo concept for your new hustle.",
    creditCost: 150,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'boombox graffiti microphone',
    defaultSize: { width: 320, height: 500 },
    permissionsRequired: [],
    routingPath: '/jroc-business-kit',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'foremanator',
    name: 'The Foremanator',
    author: 'SiteCommand',
    description: 'He doesn’t sleep. He doesn’t eat. He just yells about deadlines. Processes construction site logs.',
    creditCost: 200,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hard hat construction',
    defaultSize: { width: 340, height: 500 },
    permissionsRequired: [],
    routingPath: '/the-foremanator',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'sterileish',
    name: 'STERILE-ish™',
    author: 'Basically Compliant LLC',
    description: 'We’re basically compliant. An irreverent vibe-checker for ISO 13485, FDA, and other cleanroom logs.',
    creditCost: 500,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cleanroom laboratory science',
    defaultSize: { width: 340, height: 500 },
    permissionsRequired: [],
    routingPath: '/sterileish',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'paper-trail',
    name: 'Paper Trail P.I.',
    author: 'The Agency',
    description: "The receipts don't lie. A noir detective that scans your expense receipts and gives you the 'leads'.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'detective office noir',
    defaultSize: { width: 340, height: 500 },
    permissionsRequired: ['write:expenses', 'read:files'],
    routingPath: '/paper-trail',
    contextAwareCapabilities: ['file_upload_hook'],
    isFeatured: false,
  },
  {
    id: 'vandelay',
    name: 'Vandelay Industries',
    author: 'Art Vandelay',
    description: 'Importing, exporting, and ghosting. Generates impeccably boring, jargon-filled calendar invites to block off your time.',
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'latex architecture design',
    defaultSize: { width: 320, height: 280 },
    permissionsRequired: [],
    routingPath: '/vandelay',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'auditor-generalissimo',
    name: 'The Auditor Generalissimo™',
    author: 'The State',
    description: '“Welcome to your books, comrade. You are guilty until proven solvent.” Audits finances with oppressive precision.',
    creditCost: 250,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dossier stamp military',
    defaultSize: { width: 360, height: 600 },
    permissionsRequired: ['read:billing', 'read:expenses'],
    routingPath: '/auditor-generalissimo',
    contextAwareCapabilities: ['expense_stream', 'stripe_integration_hook'],
    isFeatured: true,
  },
  {
    id: 'vin-diesel',
    name: 'VIN Diesel',
    author: 'The Family',
    description: 'Turbocharged compliance. For family. Validates Vehicle Identification Numbers with speed and swagger.',
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'muscle car tire',
    defaultSize: { width: 320, height: 400 },
    permissionsRequired: [],
    routingPath: '/vin-diesel',
    contextAwareCapabilities: ['vin_validation_hook'],
    isFeatured: false,
  },
  {
    id: 'pam-poovey-onboarding',
    name: 'Pam Poovey: Un-HR',
    author: 'HR (Questionable)',
    description: "Sarcastic, cynical, and vaguely unhelpful HR scripts and audio. For when you're fresh out of... you know.",
    creditCost: 70,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hr office mess',
    defaultSize: { width: 320, height: 350 },
    permissionsRequired: [],
    routingPath: '/pam-poovey',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'barbara',
    name: 'Agent Barbara™',
    author: 'The Bureau',
    description: "The admin daemon you never knew you needed. She detects paperwork issues before they occur. She does not ask for thanks.",
    creditCost: 350,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'paperwork compliance government',
    defaultSize: { width: 360, height: 500 },
    permissionsRequired: ['read:documents', 'write:documents'],
    routingPath: '/barbara',
    contextAwareCapabilities: ['document_upload_hook', 'compliance_check_trigger'],
    isFeatured: true,
  },
  {
    id: 'stonks-bot',
    name: 'Stonks Bot 9000',
    author: 'WallStreetBets',
    description: 'For when you need financial advice that feels more like a dare. To the moon!',
    creditCost: 10,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'diamond hands rocket',
    defaultSize: { width: 340, height: 480 },
    permissionsRequired: ['read:market_data'],
    routingPath: '/stonks-bot',
    contextAwareCapabilities: [],
    isFeatured: true,
  },
  {
    id: 'oracle-of-delphi-valley',
    name: 'Oracle of Delphi (Valley)',
    author: 'Klepsydra Engine',
    description: 'The Folly of Venture Capital, gamified. Make your tribute to the Oracle.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'temple oracle valley',
    defaultSize: { width: 360, height: 520 },
    permissionsRequired: ['write:billing'],
    routingPath: '/oracle-of-delphi-valley',
    contextAwareCapabilities: ['tribute_hook'],
    isFeatured: true,
  }
];
