

// This file serves as a non-database source of truth for micro-app manifests.
// In a larger system, this could be stored in a database and managed via an admin interface.

export type MicroAppManifest = {
  id: string;
  name: string;
  description: string;
  author: string;
  creditCost: number;
  priceModel: 'one-time' | 'subscription' | 'included';
  imageUrl: string;
  imageHint: string;
  permissionsRequired: string[];
  routingPath: string;
  contextAwareCapabilities: string[];
  isFeatured?: boolean;
};

export const microAppManifests: MicroAppManifest[] = [
  {
    id: 'aegis-threatscope',
    name: 'Aegis ThreatScope',
    author: 'ΛΞVON OS',
    description: 'A real-time threat feed and alert dashboard for the Aegis subsystem, providing constant vigilance over your digital domain.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'radar security shield',
    permissionsRequired: ['read:security_alerts'],
    routingPath: '/aegis-threatscope',
    contextAwareCapabilities: ['security_alert_stream'],
    isFeatured: false,
  },
  {
    id: 'aegis-command',
    name: 'Aegis Command',
    author: 'ΛΞVON OS',
    description: 'Configure threat intelligence feeds and manage security baselines for the Aegis subsystem.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'shield gear settings',
    permissionsRequired: ['write:security_config'],
    routingPath: '/aegis-command',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'dr-syntax',
    name: 'Dr. Syntax',
    author: 'ΛΞVON OS',
    description: "Sarcastic, aggressive, and borderline insulting critiques of your prompts, code, or copy. It's harsh, but it works.",
    creditCost: 200,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'scalpel pen document',
    permissionsRequired: [],
    routingPath: '/dr-syntax',
    contextAwareCapabilities: [],
    isFeatured: true,
  },
  {
    id: 'beep-wingman',
    name: 'BEEP Wingman',
    author: 'ΛΞVON OS',
    description: "He's not your assistant. He's your closer. Crafts the perfect message for any tricky social situation.",
    creditCost: 120,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cockpit heart neon',
    permissionsRequired: [],
    routingPath: '/beep-wingman',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'infidelity-radar',
    name: 'Infidelity Radar',
    author: 'Spectre Intelligence',
    description: 'Because intuition deserves evidence. A suite of tools for digital investigation and behavioral analysis.',
    creditCost: 500,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'private eye dossier',
    permissionsRequired: ['integration:social_media', 'read:user_activity_logs'],
    routingPath: '/infidelity-radar',
    contextAwareCapabilities: ['osint_scan_hook', 'behavioral_analysis_hook'],
    isFeatured: false,
  },
  {
    id: 'lahey-surveillance',
    name: 'Lahey Surveillance',
    author: 'Sunnyvale Security',
    description: 'I am the liquor. And I am watching. Keep an eye on employee productivity with the Shitstorm Index™.',
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'surveillance camera bottle',
    permissionsRequired: ['read:user_activity_logs'],
    routingPath: '/lahey-surveillance',
    contextAwareCapabilities: ['user_activity_stream', 'anomaly_detection_hook'],
    isFeatured: true,
  },
  {
    id: 'kif-kroker',
    name: 'The Kif Kroker',
    author: 'DOOP',
    description: "*Sigh*. The team's conflict metrics are escalating again. Monitors Slack for passive-aggression and burnout.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'alien defeated sad',
    permissionsRequired: ['integration:slack'],
    routingPath: '/kif-kroker',
    contextAwareCapabilities: ['comms_analysis_stream'],
    isFeatured: true,
  },
  {
    id: 'lucille-bluth',
    name: 'The Lucille Bluth',
    author: 'Bluth Company',
    description: "Judgmental budgeting for your allowance. It's one banana, Michael. What could it cost, ten dollars?",
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'martini glass eye',
    permissionsRequired: ['read:expenses'],
    routingPath: '/lucille-bluth',
    contextAwareCapabilities: ['expense_entry_hook'],
    isFeatured: true,
  },
  {
    id: 'project-lumbergh',
    name: 'Project Lumbergh',
    author: 'Initech',
    description: "Yeeeeah, about those meetings... Analyzes invites for pointlessness and generates passive-aggressive decline memos.",
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'red stapler office',
    permissionsRequired: ['read:calendar'],
    routingPath: '/project-lumbergh',
    contextAwareCapabilities: ['calendar_event_hook'],
    isFeatured: true,
  },
  {
    id: 'winston-wolfe',
    name: 'The Winston Wolfe',
    author: 'The Fixer',
    description: "Bad review? Thirty minutes away. I'll be there in ten. Solves online reputation problems with surgical precision.",
    creditCost: 300,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'sharp suit cleaning',
    permissionsRequired: ['integration:social_media'],
    routingPath: '/winston-wolfe',
    contextAwareCapabilities: ['reputation_alert_stream'],
    isFeatured: true,
  },
  {
    id: 'rolodex',
    name: 'The Rolodex',
    author: 'Sterling Cooper',
    description: "Analyzes new or existing contacts against a job description to determine fit and generate outreach assets.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'vintage rolodex office',
    permissionsRequired: [],
    routingPath: '/rolodex',
    contextAwareCapabilities: [],
    isFeatured: true,
  },
  {
    id: 'jroc-business-kit',
    name: "J-ROC'S BIZ KIT™",
    author: 'Roc Pile Inc.',
    description: "Get dat cheddar legit, my dawg. Generates a business name, tagline, and logo concept for your new hustle.",
    creditCost: 150,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'boombox graffiti microphone',
    permissionsRequired: [],
    routingPath: '/jroc-business-kit',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'the-foremanator',
    name: 'The Foremanator',
    author: 'SiteCommand',
    description: 'He doesn’t sleep. He doesn’t eat. He just yells about deadlines. Processes construction site logs.',
    creditCost: 200,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hard hat construction',
    permissionsRequired: [],
    routingPath: '/the-foremanator',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'sterileish',
    name: 'STERILE-ish™',
    author: 'Basically Compliant LLC',
    description: 'We’re basically compliant. An irreverent vibe-checker for ISO 13485, FDA, and other cleanroom logs.',
    creditCost: 500,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'cleanroom laboratory science',
    permissionsRequired: [],
    routingPath: '/sterileish',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'paper-trail',
    name: 'Paper Trail P.I.',
    author: 'The Agency',
    description: "The receipts don't lie. A noir detective that scans your expense receipts and gives you the 'leads'.",
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'detective office noir',
    permissionsRequired: ['write:expenses', 'read:files'],
    routingPath: '/paper-trail',
    contextAwareCapabilities: ['file_upload_hook'],
    isFeatured: false,
  },
  {
    id: 'vandelay',
    name: 'Vandelay Industries',
    author: 'Art Vandelay',
    description: 'Importing, exporting, and ghosting. Generates impeccably boring, jargon-filled calendar invites to block off your time.',
    creditCost: 50,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'latex architecture design',
    permissionsRequired: [],
    routingPath: '/vandelay',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'usage-monitor',
    name: 'Usage Monitor',
    author: 'ΛΞVON OS',
    description: 'Track your monthly Agent Action consumption against your plan limits. The core value metric.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'gauge chart data',
    permissionsRequired: ['read:billing'],
    routingPath: '/usage-monitor',
    contextAwareCapabilities: ['billing_update_event'],
    isFeatured: false,
  },
  {
    id: 'kendra',
    name: 'KENDRA.exe',
    author: 'The Algorithm',
    description: 'Kendall Roy’s delusion. Kris Jenner’s strategy. Your unhinged marketing agent. This is branding with beef.',
    creditCost: 1000,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'fashion high-heels neon',
    permissionsRequired: [],
    routingPath: '/kendra',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'stonks-bot',
    name: 'Stonks Bot',
    author: 'r/wallstreetbets',
    description: 'This is not financial advice. Get unhinged, extremely bullish stock tips from a certified degen.',
    creditCost: 42,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'rocket moon diamond',
    permissionsRequired: [],
    routingPath: '/stonks-bot',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'auditor-generalissimo',
    name: 'The Auditor Generalissimo™',
    author: 'The State',
    description: '“Welcome to your books, comrade. You are guilty until proven solvent.” Audits finances with oppressive precision.',
    creditCost: 250,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dossier stamp military',
    permissionsRequired: ['read:billing', 'read:expenses'],
    routingPath: '/auditor-generalissimo',
    contextAwareCapabilities: ['expense_stream', 'stripe_integration_hook'],
    isFeatured: true,
  },
  {
    id: 'orphean-oracle',
    name: 'The Orphean Oracle',
    author: 'ΛΞVON OS',
    description: 'Descends into the data underworld to return with a story. A metaphorical, visual narrative of your business data.',
    creditCost: 0,
    priceModel: 'included',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'lyre strings data',
    permissionsRequired: ['read:business_data'],
    routingPath: '/orphean-oracle',
    contextAwareCapabilities: ['data_stream_analysis'],
    isFeatured: false,
  },
  {
    id: 'vin-diesel',
    name: 'VIN Diesel',
    author: 'The Family',
    description: 'Turbocharged compliance. For family. Validates Vehicle Identification Numbers with speed and swagger.',
    creditCost: 90,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'muscle car tire',
    permissionsRequired: [],
    routingPath: '/vin-diesel',
    contextAwareCapabilities: ['vin_validation_hook'],
    isFeatured: false,
  },
  {
    id: 'pam-poovey-onboarding',
    name: 'Pam Poovey: Un-HR',
    author: 'HR (Questionable)',
    description: "Sarcastic, cynical, and vaguely unhelpful HR scripts and audio. For when you're fresh out of... you know.",
    creditCost: 70,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'hr office mess',
    permissionsRequired: [],
    routingPath: '/pam-poovey',
    contextAwareCapabilities: [],
    isFeatured: false,
  },
  {
    id: 'barbara',
    name: 'Agent Barbara™',
    author: 'The Bureau',
    description: "The admin daemon you never knew you needed. She detects paperwork issues before they occur. She does not ask for thanks.",
    creditCost: 350,
    priceModel: 'one-time',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'paperwork compliance government',
    permissionsRequired: ['read:documents', 'write:documents'],
    routingPath: '/barbara',
    contextAwareCapabilities: ['document_upload_hook', 'compliance_check_trigger'],
    isFeatured: true,
  }
];
